[[snippets]]
  description = "Check HTTPS certificate expiration"
  command = "echo | openssl s_client -connect <domain>:<port=443> 2>/dev/null |openssl x509 -dates -noout"
  output = ""

[[snippets]]
  description = "Download and bootstrap dotfiles"
  command = "eval $(curl d.ndj.la | bash)"
  output = ""

[[snippets]]
  description = "AWS KMS Decrypt CLI"
  command = "aws kms decrypt --region <region=us-west-2> --ciphertext-blob fileb://<file=encrypted> --query Plaintext --output text | base64 --decode"
  output = ""

[[snippets]]
  description = "AWS KMS Encrypt CLI"
  command = "aws kms encrypt --region <region=us-west-2> --key-id <keyid=alias/Key> --plaintext <plaintext=datatoencrypt> --query CiphertextBlob --output text | base64 --decode > <file=encrypted>"
  output = ""

[[snippets]]
  description = "Get Instance User Data"
  command = "curl -s http://169.254.169.254/latest/user-data | less"
  output = ""

[[snippets]]
  description = "Short docker status"
  command = "docker ps --format \"table {{.Names}}\\t{{.Status}}\""
  output = ""
