[[snippets]]
  description = "Check HTTPS certificate expiration"
  command = "echo | openssl s_client -connect <domain>:443 2>/dev/null |openssl x509 -dates -noout"
  output = ""

[[snippets]]
  description = "Download and bootstrap dotfiles"
  command = "eval $(curl d.ndj.la | bash)"
  output = ""
